name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Check commit messages
      uses: wagoid/commitlint-github-action@v5

    - name: Check code formatting
      run: npm run format:check

    - name: Check for file size increases
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "frontend/build/**/*.{js,css,html,json}"

    - name: Run security audit
      run: npm audit 